import { color } from "../utils.js";

export const installationLogs = [
 // [Texto, milissegundos, tabulação]
    ["Inicializando QTDSystemOS...", 3000, 0],
    ["Instalando bibliotecas...", 200, 0],  
        [color("-- pale_moon_anomaly.oct",      QTDOSPROCESS_HEXCOLOR),     500, 1],
        [color("-- coords_mapping_121.oct",     QTDOSPROCESS_HEXCOLOR),     100, 1],
        [color("-- game_tree_nodes.oct",        QTDOSPROCESS_HEXCOLOR),     2000, 1],
        [color("-- session_rollback.oct",       QTDOSPROCESS_HEXCOLOR),     100, 1],
        [color("-- clearing_perimeter.oct",     QTDOSPROCESS_HEXCOLOR),     100, 1],
        [color("-- deep_cavern_ambience.oct",   QTDOSPROCESS_HEXCOLOR),     100, 1],
        [color("-- settlement_pacified.oct",    QTDOSPROCESS_HEXCOLOR),     100, 1],
        [color("-- buried_chest_log.oct",       QTDOSPROCESS_HEXCOLOR),     500, 1],
        [color("-- despair_state_0.oct",        QTDOSPROCESS_HEXCOLOR),     100, 1],
        [color("-- greed_evaluation.oct",       QTDOSPROCESS_HEXCOLOR),     600, 1],
        [color("-- player_input_handler.oct",   QTDOSPROCESS_HEXCOLOR),     700, 1],
        [color("-- bootstrap_init.oct",         QTDOSPROCESS_HEXCOLOR),     1000, 1],
        [color("-- subterranean_torch.oct",     QTDOSPROCESS_HEXCOLOR),     10, 1],
        [color("-- villager_dialogue_tree.oct", QTDOSPROCESS_HEXCOLOR),     100, 1],
        [color("-- undiscovered_outcomes.oct",  QTDOSPROCESS_HEXCOLOR),     2000, 1],
    ["<p></p>", 1, 0],
    ["Bibliotecas instaladas!", 1, 0],
    [`Data da instalação: ${new Date()}`, 1, 0],
    ["Versão do OS: __QTDOS 1.0.0.x-map-ver64bits", 100, 0],
        ["CPU Health: 100%", 500, 1],
        ["Firmware setup: QTDOS_FMW", 5000, 1],
        ["Kernel: QTDOS_KN1.7", 1000, 1],
            [`${color(`[${Date.now()}]`, QTDOSTIMEMS_HEXCOLOR)} ${color("qtdos kernel:", QTDOSPROCESS_HEXCOLOR)} Booting QTDOS x86 Core Core v1.0.0-release`, 100, 2],
            [`${color(`[${Date.now()}]`, QTDOSTIMEMS_HEXCOLOR)} ${color("qtdos kernel:", QTDOSPROCESS_HEXCOLOR)} CPU0: GenuineIntel / QTDOS Virtual CPU @ 2.40GHz`, 100, 2],
            [`${color(`[${Date.now()}]`, QTDOSTIMEMS_HEXCOLOR)} ${color("qtdos kernel:", QTDOSPROCESS_HEXCOLOR)} BIOS-e820: [mem 0x0000000000000000-0x000000000009ffff] usable`, 100, 2],
            [`${color(`[${Date.now()}]`, QTDOSTIMEMS_HEXCOLOR)} ${color("qtdos kernel:", QTDOSPROCESS_HEXCOLOR)} ACPI: Core revision 20260520 table walkthrough complete`, 100, 2],
            [`${color(`[${Date.now()}]`, QTDOSTIMEMS_HEXCOLOR)} ${color("qtdos kernel:", QTDOSPROCESS_HEXCOLOR)} ACPI: HPET id: 0x8086a201 base: 0xfed00000 length: 0x400`, 100, 2],
            [`${color(`[${Date.now()}]`, QTDOSTIMEMS_HEXCOLOR)} ${color("qtdos storage:", QTDOSPROCESS_HEXCOLOR)} VFS: Mounting root filesystem (octfs) on /dev/sda1`, 500, 2],
    ["<p></p>", 1, 0],            
            [`${color(`[${Date.now()}]`, QTDOSTIMEMS_HEXCOLOR)} ${color("qtdos kernel:", QTDOSPROCESS_HEXCOLOR)} Inicializando QTDOS Core v1.0.0-release (x86_64)`, 100, 2],
            [`${color(`[${Date.now()}]`, QTDOSTIMEMS_HEXCOLOR)} ${color("qtdos kernel:", QTDOSPROCESS_HEXCOLOR)} Linha de comando do boot: ro quiet splash root=UUID=qtdos-root`, 100, 2],
            [`${color(`[${Date.now()}]`, QTDOSTIMEMS_HEXCOLOR)} ${color("qtdos kernel:", QTDOSPROCESS_HEXCOLOR)} CPU0: Intel(R) Core(TM) / QTDOS Virtual CPU @ 3.20GHz`, 100, 2],
            [`${color(`[${Date.now()}]`, QTDOSTIMEMS_HEXCOLOR)} ${color("qtdos kernel:", QTDOSPROCESS_HEXCOLOR)} BIOS-e820: [mem 0x0000000000000000-0x000000000009ffff] usavel`, 100, 2],
            [`${color(`[${Date.now()}]`, QTDOSTIMEMS_HEXCOLOR)} ${color("qtdos kernel:", QTDOSPROCESS_HEXCOLOR)} BIOS-e820: [mem 0x00000000000a0000-0x00000000000fffff] reservado pela BIOS`, 100, 2],
            [`${color(`[${Date.now()}]`, QTDOSTIMEMS_HEXCOLOR)} ${color("qtdos kernel:", QTDOSPROCESS_HEXCOLOR)} BIOS-e820: [mem 0x0000000000100000-0x000000007fffffff] usavel (Total: 2048 MB)`, 100, 2],
            [`${color(`[${Date.now()}]`, QTDOSTIMEMS_HEXCOLOR)} ${color("qtdos kernel:", QTDOSPROCESS_HEXCOLOR)} Procurando tabelas ACPI... Sucesso.`, 100, 2],
            [`${color(`[${Date.now()}]`, QTDOSTIMEMS_HEXCOLOR)} ${color("qtdos kernel:", QTDOSPROCESS_HEXCOLOR)} ACPI: Controladora LAPIC encontrada no endereco 0xfee00000`, 100, 2],
            [`${color(`[${Date.now()}]`, QTDOSTIMEMS_HEXCOLOR)} ${color("qtdos kernel:", QTDOSPROCESS_HEXCOLOR)} Alocador de paginas de memoria (MMU) ativado com sucesso.`, 100, 2],
            [`${color(`[${Date.now()}]`, QTDOSTIMEMS_HEXCOLOR)} ${color("qtdos kernel:", QTDOSPROCESS_HEXCOLOR)} Protecao de memoria de Kernel (SMEP/SMAP) ativada.`, 100, 2],
            [`${color(`[${Date.now()}]`, QTDOSTIMEMS_HEXCOLOR)} ${color("qtdos kernel:", QTDOSPROCESS_HEXCOLOR)} Alocando tabela de vetores de interrupcao (IDT)...`, 100, 2],
            [`${color(`[${Date.now()}]`, QTDOSTIMEMS_HEXCOLOR)} ${color("qtdos kernel:", QTDOSPROCESS_HEXCOLOR)} IDT configurada com 256 entradas de interrupcao mascaráveis.`, 100, 2],
            [`${color(`[${Date.now()}]`, QTDOSTIMEMS_HEXCOLOR)} ${color("qtdos kernel:", QTDOSPROCESS_HEXCOLOR)} Inicializando relogio de alta precisao HPET em 0xfed00000`, 100, 2],
            [`${color(`[${Date.now()}]`, QTDOSTIMEMS_HEXCOLOR)} ${color("qtdos kernel:", QTDOSPROCESS_HEXCOLOR)} Registrando subsistema PCI Express (PCIe bus 00)`, 100, 2],
            [`${color(`[${Date.now()}]`, QTDOSTIMEMS_HEXCOLOR)} ${color("qtdos kernel:", QTDOSPROCESS_HEXCOLOR)} pci 0000:00:01.0: [8086:29c0] VGA compatible controller encontrado`, 100, 2],
            [`${color(`[${Date.now()}]`, QTDOSTIMEMS_HEXCOLOR)} ${color("qtdos kernel:", QTDOSPROCESS_HEXCOLOR)} Console de video inicializado: Modos de resolucao detectados via VBE VESA`, 100, 2],
            [`${color(`[${Date.now()}]`, QTDOSTIMEMS_HEXCOLOR)} ${color("qtdos input:", QTDOSPROCESS_HEXCOLOR)} Inicializando barramento PS/2 para dispositivos de entrada`, 100, 2],
            [`${color(`[${Date.now()}]`, QTDOSTIMEMS_HEXCOLOR)} ${color("qtdos input:", QTDOSPROCESS_HEXCOLOR)} Teclado AT Tradicional de 101/104 teclas detectado em irq 1`, 100, 2],
            [`${color(`[${Date.now()}]`, QTDOSTIMEMS_HEXCOLOR)} ${color("qtdos input:", QTDOSPROCESS_HEXCOLOR)} Mouse PS/2 Generico detectado em irq 12`, 100, 2],
            [`${color(`[${Date.now()}]`, QTDOSTIMEMS_HEXCOLOR)} ${color("qtdos usb:", QTDOSPROCESS_HEXCOLOR)} Controlador USB xHCI inicializado (0000:00:14.0)`, 100, 2],
            [`${color(`[${Date.now()}]`, QTDOSTIMEMS_HEXCOLOR)} ${color("qtdos usb:", QTDOSPROCESS_HEXCOLOR)} Hub USB raiz de 4 portas detectado`, 100, 2],
            [`${color(`[${Date.now()}]`, QTDOSTIMEMS_HEXCOLOR)} ${color("qtdos storage:", QTDOSPROCESS_HEXCOLOR)} Inicializando controladora AHCI SATA (SATA Express)`, 100, 2],
            [`${color(`[${Date.now()}]`, QTDOSTIMEMS_HEXCOLOR)} ${color("qtdos storage:", QTDOSPROCESS_HEXCOLOR)} ata1: Dispositivo SATA detectado - QEMU HARDDISK (20 GB)`, 100, 2],
            [`${color(`[${Date.now()}]`, QTDOSTIMEMS_HEXCOLOR)} ${color("qtdos storage:", QTDOSPROCESS_HEXCOLOR)} sda: sda1 (Tabela de particoes MBR detectada)`, 100, 2],
            [`${color(`[${Date.now()}]`, QTDOSTIMEMS_HEXCOLOR)} ${color("qtdos storage:", QTDOSPROCESS_HEXCOLOR)} VFS: Montando sistema de arquivos raiz (octfs) em /dev/sda1`, 100, 2],
            [`${color(`[${Date.now()}]`, QTDOSTIMEMS_HEXCOLOR)} ${color("qtdos octfs:", QTDOSPROCESS_HEXCOLOR)} Verificando integridade da particao... Status: LIMPO.`, 100, 2],
            [`${color(`[${Date.now()}]`, QTDOSTIMEMS_HEXCOLOR)} ${color("qtdos octfs:", QTDOSPROCESS_HEXCOLOR)} Carregando indices de caminhos virtuais e arvores de decisao`, 100, 2],
            [`${color(`[${Date.now()}]`, QTDOSTIMEMS_HEXCOLOR)} ${color("qtdos octfs:", QTDOSPROCESS_HEXCOLOR)} Indexados 15 arquivos estruturais (.oct) na pasta do sistema`, 100, 2],
            [`${color(`[${Date.now()}]`, QTDOSTIMEMS_HEXCOLOR)} ${color("qtdos systemd:", QTDOSPROCESS_HEXCOLOR)} Inicializando gerenciador de servicos principais...`, 100, 2],
            [`${color(`[${Date.now()}]`, QTDOSTIMEMS_HEXCOLOR)} ${color("qtdos systemd:", QTDOSPROCESS_HEXCOLOR)} Servico de Logs de Eventos (syslogd) iniciado.`, 100, 2],
            [`${color(`[${Date.now()}]`, QTDOSTIMEMS_HEXCOLOR)} ${color("qtdos systemd:", QTDOSPROCESS_HEXCOLOR)} Carregando interpretador de comandos interativos (QShell)...`, 100, 2],
    ["<p></p>", 1, 0],   
    [`${color(`[${Date.now()}]`, QTDOSTIMEMS_HEXCOLOR)} ${color("qtdos systemd:", QTDOSPROCESS_HEXCOLOR)} Shell inicializado. Bem vindo ao QTDOS. Pressione na tela ou qualquer tecla para iniciar.`, 1, 0],
];

export const setupLogs = [
    ["Inicializando QTDSystemOS...", 3000, 0],
    ["Identificando bibliotecas instaladas...", 1000, 0],  
        [color("-- pale_moon_anomaly.oct",      QTDOSPROCESS_HEXCOLOR),     50, 1],
        [color("-- coords_mapping_121.oct",     QTDOSPROCESS_HEXCOLOR),     50, 1],
        [color("-- game_tree_nodes.oct",        QTDOSPROCESS_HEXCOLOR),     50, 1],
        [color("-- session_rollback.oct",       QTDOSPROCESS_HEXCOLOR),     50, 1],
        [color("-- clearing_perimeter.oct",     QTDOSPROCESS_HEXCOLOR),     50, 1],
        [color("-- deep_cavern_ambience.oct",   QTDOSPROCESS_HEXCOLOR),     50, 1],
        [color("-- settlement_pacified.oct",    QTDOSPROCESS_HEXCOLOR),     50, 1],
        [color("-- buried_chest_log.oct",       QTDOSPROCESS_HEXCOLOR),     50, 1],
        [color("-- despair_state_0.oct",        QTDOSPROCESS_HEXCOLOR),     50, 1],
        [color("-- greed_evaluation.oct",       QTDOSPROCESS_HEXCOLOR),     50, 1],
        [color("-- player_input_handler.oct",   QTDOSPROCESS_HEXCOLOR),     50, 1],
        [color("-- bootstrap_init.oct",         QTDOSPROCESS_HEXCOLOR),     50, 1],
        [color("-- subterranean_torch.oct",     QTDOSPROCESS_HEXCOLOR),     50, 1],
        [color("-- villager_dialogue_tree.oct", QTDOSPROCESS_HEXCOLOR),     50, 1],
        [color("-- undiscovered_outcomes.oct",  QTDOSPROCESS_HEXCOLOR),     50, 1],
    ["<p></p>", 1, 0],
    [`Bibliotecas encontradas: 15 ${color("(0 restantes)", QTDOSHEAL_HEXCOLOR)}`, 100, 0], 
    [`${color(`[${Date.now()}]`, QTDOSTIMEMS_HEXCOLOR)} ${color("qtdos systemd:", QTDOSPROCESS_HEXCOLOR)} Shell inicializado. Bem vindo ao QTDOS. Pressione na tela ou qualquer tecla para iniciar.`, 1, 0],
]
